AWSTemplateFormatVersion: 2010-09-09
Description: |
  PoC-SAM
  SAM Template to build the lambdas for Autonomous HighLights Platform PoC
Resources:
  labelDetection:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: labelDetection.lambda_handler
      CodeUri: labelDetection/src
      Role: 'arn:aws:iam::693949087897:role/service-role/labelDetectionLambdaRole'
      Runtime: python3.7
  jsonAppender:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: jsonAppender.lambda_handler
      CodeUri: jsonAppender/src
      Role: 'arn:aws:iam::693949087897:role/service-role/jsonAppenderRole'
      Runtime: python3.7
  videoReducer:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: videoReducer.lambda_handler
      CodeUri: videoReducer/src
      Role: 'arn:aws:iam::693949087897:role/service-role/videoReducerRole'
      Runtime: python3.7
  ahlvideos:
    Type: 'AWS::S3::Bucket'
    Properties:
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: vidoes
                  - Name: suffix
                    Value: .mp4
            Function: >-
              videoReducer
          - Event: 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: outConvert
                  - Name: suffix
                    Value: .jpg
            Function: >-
              labelDetection
          - Event: 's3:ObjectCreated:Put'
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: outConvert
                  - Name: suffix
                    Value: .json
            Function: >-
              jsonAppender
    DependsOn:
      - videoReducer
      - jsonAppender
      - labelDetection
